version: 1.0.{build}
install:
- cmd: choco install csx --source https://www.nuget.org/api/v2 --pre
build_script:
- cmd: >-
    cd build
    
    csx build.csx
test: off
artifacts:
- path: ../tmp/*.nupkg
  name: NuGet Packages
deploy:
  provider: NuGet  
  api_key:
    secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm
  skip_symbols: false  
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true